

###get users from DB
GET http://localhost:3000/api/users HTTP/1.1

### get if single user exsists
GET http://localhost:3000/api/users/JuLoe HTTP/1.1

### GET a single user which doesn't exist
GET http://localhost:3000/api/users/noelNotExist HTTP/1.1

### delete user
DELETE  http://localhost:3000/api/users/UswrSamet HTTP/1.1

### add a User to dB
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Samet",
    "username": "UswrSamet",
    "password": "SrrtSamet123"
}
### LOGIN  username und passwort abfragen/ 
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "UswrSamet",
    "password": "SrrtSamet123"
}

### PROFILE seite eines users / meine Seite
GET http://localhost:3000/api/me HTTP/1.1


### LOGOUT
POST http://localhost:3000/api/logout HTTP/1.1